name: Deploy via FTP to amayaia.com

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   bh8936.banahosting.com   # <- host EXACTO del certificado
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps                     # FTPS explícito
          port: 21
          local-dir: ./                     # raíz del repo
          server-dir: /amayaia.com/         # <- docroot correcto en tu cuenta
          log-level: verbose
          dangerous-clean-slate: false
          exclude: |
            .git
            .git/**
            .github/**
            **/.DS_Store
            .idea/**
            .vscode/**
            node_modules/**
            **/*.md
            backups/**
            uploads/**
            tmp/**
