name: Deploy via FTP to amayaia.com

on:
  push:
    branches: [ main ]          # corre en cada push a main
  workflow_dispatch:             # permite ejecutarlo manualmente

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp               # o usa ${{ secrets.FTP_PROTOCOL }} si lo definiste
          port: 21                    # o usa ${{ secrets.FTP_PORT }}
          local-dir: ./               # raíz del repo
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}  # ajusta si tu raíz es distinta
          #dangerous-clean-slate: true   # (OPCIONAL) solo la primera vez si quieres limpiar todo
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/*.md
            .idea/**
            .vscode/**
            backups/**
            uploads/**
            tmp/**
            **/*.ai
            **/*.psd
            **/*.sketch
