- name: Deploy
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ${{ secrets.FTP_HOST }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    protocol: ftp
    port: 21
    local-dir: ./
    server-dir: /amayaia.com/         # o /public_html/ si ese es tu docroot
    log-level: verbose
    dangerous-clean-slate: false
    exclude: |
      # Git
      .git/**
      **/.git/**
      .git*
      **/.git*
      .github/**
      **/.github/**
      .gitattributes
      .gitignore

      # SO/editores
      **/.DS_Store
      .idea/**
      .vscode/**

      # Node y docs
      node_modules/**
      **/*.md

      # Carpetas del server que no quieres tocar
      backups/**
      uploads/**
      tmp/**
