name: Deploy via FTP to amayaia.com

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}          # usa el hostname real del servidor
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /amayaia.com/               # si tu contenido está ahí (o /public_html/)
          log-level: verbose
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/*.md
            .idea/**
            .vscode/**
            backups/**
            uploads/**
            tmp/**
